### ISSUE TITLE
VCP ValueError 

### ISSUE THREAD

**Issue by mabgh** [digitaltrails/vdu_controls#1]
INFO: checking for config file '/x/.config/vdu_controls/U32R59x_H1AK500000.conf'
INFO: checking for config file '/x/.config/vdu_controls/U32R59x.conf'
ERROR:
 Traceback (most recent call last):
  File "/usr/local/bin/vdu_controls", line 1181, in <module>
    main()
  File "/usr/local/bin/vdu_controls", line 998, in main
    main_window = DdcMainWidget(enabled_vcp_codes, args.warnings, args.debug, args.sleep_multiplier, detect_vdu_hook)
  File "/usr/local/bin/vdu_controls", line 748, in __init__
    vdu_widget = DdcVduWidget(vdu, enabled_vcp_codes, warnings)
  File "/usr/local/bin/vdu_controls", line 699, in __init__
    control = DdcComboBox(vdu, capability)
  File "/usr/local/bin/vdu_controls", line 654, in __init__
    raise ValueError('VCP_CODE {} value {} is not in allowed list: {}'.format(
ValueError: VCP_CODE 60 value 06 is not in allowed list: ['12', '0f']

ddcutil detect
Invalid display
   I2C bus:             /dev/i2c-4
   EDID synopsis:
      Mfg id:           LGD
      Model:            
      Serial number:    
      Manufacture year: 2018
      EDID version:     1.4
   DDC communication failed
   This is an eDP laptop display. Laptop displays do not support DDC/CI.

Display 1
   I2C bus:             /dev/i2c-10
   EDID synopsis:
      Mfg id:           SAM
      Model:            U32R59x
      Serial number:    H1AK500000
      Manufacture year: 2018
      EDID version:     1.3
   VCP version:         2.0

**Comment by digitaltrails** [comment]
Thanks for the feedback. It iooks like I need to ignore built in laptop displays. I don't have access to a Linux laptop, but I can fake ddutils output for testing.  Hopefully this will be an easy fix, perhaps a day or so. I just need some free time to get on to it.

**Comment by digitaltrails** [comment]
Could you post the output from:
ddcutil detect --terse

**Comment by mabgh** [comment]
ddcutil detect --terse
Invalid display
   I2C bus:             /dev/i2c-4
   Monitor:             LGD::

Display 1
   I2C bus:             /dev/i2c-10
   Monitor:             SAM:U32R59x:H1AK500000

don't hesitate to ask for assistance  (test etc.)

**Comment by digitaltrails** [comment]
> ddcutil detect --terse
> Invalid display
> I2C bus: /dev/i2c-4
> Monitor: LGD::
> 
> Display 1
> I2C bus: /dev/i2c-10
> Monitor: SAM:U32R59x:H1AK500000
> 
> don't hesitate to ask for assistance (test etc.)

Thanks that will be helpful in testing the code I'll have to add to properly ignore laptop displays.  

It seems like vdu_controls is getting past it's monitor detection phase. Laptop displays may just be a side issue and perhaps they are not the real cause of the exception you reported.  At the point of the exception the code was trying to assemble a set of controls for display 1.  It appears to be getting an unexpected value for VCP code 60 which is the code for monitor input-source, the bad value being 06 (according to the standard 06 is Composite video 2 - see **ddcutil --verbose vcpinfo**).  The reported valid values from **ddcutil --display 1 capabilities** state the values for this monitor should 12 (HDMI-1) or 0f (Display-Port1), so 06 is definitely unexpected.  If you're not particularly interested in a control for input-source, then **vdu_controls --hide input-source** would not try to add that control and might run OK.  If you really do want an a control for input-source, then the man page referenced from the README.md does contain some info on "VDU/VDU-model config files" can work around such an issue (with the example discussed also being for VCP code 60, because my LG monitor claims to have more input-sources that it physically has).

I'm also working on some code to avoid raising exceptions for unexpected values.  Hopefully today depending on other commitments.

**Comment by digitaltrails** [comment]
I amended vdu_controls.py in commit c3824e726f02ce9d661a64fc6e3792152bc42b77
Hopefully that commit should correctly handle this issue.  The code now ignores built-in LCD displays (or any displays the ddcutil reports to be an "Invalid display").  If a monitor has a invalid/unexpected value for a combo-box control, a warning will popup and the offending control will not show in the GUI.

Hopefully this should deal with the issue and be more robust in general.

**Comment by digitaltrails** [comment]
> ddcutil detect --terse
> Invalid display
> I2C bus: /dev/i2c-4
> Monitor: LGD::
> 
> Display 1
> I2C bus: /dev/i2c-10
> Monitor: SAM:U32R59x:H1AK500000
> 
> don't hesitate to ask for assistance (test etc.)

Thanks for your kind offer.  When you have a spare moment, if you'd like to try the updated version it would be good to know if the works on the real deal.  No rush.

**Comment by mabgh** [comment]
First, your hint to use the hide-option worked. I had then a second problematic VCP code D6 with illegal value 00. By adding '--hide power-mode' this was ignored too and application ran as expected.
Second, your hint to use a edited vdu configuration file worked as well.
Last, the updated version (of course, no options, no configuration) displays message boxes with the respective errors and then continues displaying the controls. Everything, inclusive system tray, is functioning well.
Thank you for this nice application.

**Comment by digitaltrails** [comment]
> First, your hint to use the hide-option worked. I had then a second problematic VCP code D6 with illegal value 00. By adding '--hide power-mode' this was ignored too and application ran as expected.
> Second, your hint to use a edited vdu configuration file worked as well.
> Last, the updated version (of course, no options, no configuration) displays message boxes with the respective errors and then continues displaying the controls. Everything, inclusive system tray, is functioning well.
> Thank you for this nice application.

Thanks again for the feedback.  My LG monitor may also be misreporting it's power-mode options, it appears to not reporting one that it appears to have.   It's good to know that all these options and variations work correctly on you system.  Plus it's good to know someone else is getting some use of the application.   I'll closing the issue.
