### ISSUE TITLE
Unknown combo box values cause failure to show or app to close

### ISSUE THREAD

**Issue by crashmatt** [digitaltrails/vdu_controls#10]
My monitor changes color preset to an undefined value when display mode is changed.  This either prevents the color preset from being shown or stops the monitor from being shown.

Simple fix is to add an "unknown:val" to the combo box instead of throwing an error.  This allows the user to continue and fix it later if required.

By skipping the ValueError it fails to notify the user of the potential fix.  Some more work required.

![image](https://user-images.githubusercontent.com/351261/141108083-0e0dd0e3-0437-435c-be23-bea0afc24145.png)

**Comment by digitaltrails** [comment]
The problem of undocumented "features" and values is a sticky one.  I think a ddcutil user bricked their monitor by trying an unsupported feature.  My own LG monitor provides a VCP standard feature for Input Source, but includes a value for an input source that does not exists, is it safe to choose that source?

In your situation the undocumented value seems pretty harmless.  The correct approach is for the user to add the unsupported value to the metadata.  The problem, as I see it, is that the application should not fall over before allowing the user to make that correction.  On the other had I don't want to get too liberal about walking off the metadata definitions for fear of enabling some manufacturer's quality control bricking-code.

If I interpret your situation correctly, there are two use cases:

1. If an out of bounds value is encountered when vdu_controls is initialising, the message about extending the metadata comes up, the offending code is removed,  the application successfully starts up,  and the user is free to go on and correct the metadata.
2. If and out of bounds value is encountered after initialisation while in normal operation, the application raises a dialog and then exits without the user being given a chance to fix the metadata.

I'm relatively happy with use-case-1, and in use-case-2, the user can restart and will be in use-case-1.  I'm not happy that use-case-2 leaves the user dumped out of the application.  

I've been able to test some of this using an old HP monitor that has presets that work (ddcutil reports that my main LG 4K monitor has three VCP "color presets", but the monitor does not show them on it's inbuilt menu, rather its inbuilt menu has a 11 non-standard "picture modes", fooling with the presets is not something I feel comfortable with).

At the moment I'm considering what to do, but this is what I'm thinking at the moment for the two user-cases:

1. Pretty much as is, but maybe with a message that advises the user to use the settings panel to edit the metadata.

2. More like 1, bring up an error dialog with the same editing instructions, then use the _restarting due to config change_ dialog, which would result in user remaining in the application with the offending control removed, at which point they could again go to the settings panel and edit the metadata.

On a brief look it does seem easy to add the unknown value to the self.keys of VduControlComboBox and carry on.   But I feel the application should also add the correction to the metadata so it can be easily edited. I'm hesitant to go down this path, both because of previously stated concerns and also because it gets untidy by crosses boundaries in the code (which has already become quite messy due to creeping featuritis).  

I definitely think it would be wise to chop back the initial set of enabled controls to those that are likely to work without any manufacturer VCP doggyness (brightness, contrast and volume are a pretty safe bet).

**Comment by digitaltrails** [comment]
In both error scenarios I think I'm going to 

1. Always raise an annoying dialog dialog suggesting the metadata should be amended.
2. As you suggested add a temporary placeholder value.  Possibly the value should be unselectable, so they can go back to a valid value, but cannot pick an invalid one unless they go to the trouble of adding it to the metadata.

This means the user probably won't just ignore the issue, but they can carry on for the moment, and they can (hopefully) use the application to set the value back to something "valid" if necessary.

**Comment by digitaltrails** [comment]
> In both error scenarios I think I'm going to
> 
> 1. Always raise an annoying dialog dialog suggesting the metadata should be amended.
> 2. As you suggested add a temporary placeholder value.  Possibly the value should be unselectable, so they can go back to a valid value, but cannot pick an invalid one unless they go to the trouble of adding it to the metadata.
> 
> This means the user probably won't just ignore the issue, but they can carry on for the moment, and they can (hopefully) use the application to set the value back to something "valid" if necessary.

Implemented as described.  Making the offending value unselectable could be revisited if it proves to be a nuisance.

**Comment by crashmatt** [comment]
Blocking writes of unknown values is ok.  I suspect my monitor is setting some placeholder values when in an alternative mode.  For example, color preset is set to zero when display mode is set to Game/Movie.
Then color preset is set to 0x1 on both monitor when the preset is set to normal.
Only one monitor has the description for color preset 0x01=sRGB.

Being able to edit the capabilities directly is easy.  Maybe not obvious but it is easy.

**Comment by digitaltrails** [comment]
There's another case where a combo box setting can be set to an out of range value: when the user changes the monitor settings externally and then presses "refresh settings from monitors".   It's a simple one line fix which I will check in shortly.

As part of testing these changes changes I've been exploring my LG monitor's non-standard VCP code 15 for Picture Mode (Custom, Vivid, REC709, EBU,  etc).  The metadata the monitor returns for VCP 15 has more mode-values the monitor's own-menu.  So I started stepping through the modes by setting them using the monitor's menu - which is how I tripped over this new variant of the issue.   So far no mode-value that I've set via the monitor's menu corresponds to any of the values reported back in the monitor's metadata. 

It does seem that beyond brightness and contrast there be dragons, so perhaps enabling unknown-codes should require a little effort.

These CNC and invalid-value fixes have become quite useful, thanks for working with me on this.
