### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by 0xCUB3** [digitaltrails/vdu_controls#13]
Is it possible to map a keyboard shortcut to change brightness with VDU?

**Comment by digitaltrails** [comment]
Thanks for the feedback.  To clarify, would this be:

1. Shortcuts that are only active when inside the vdu_controls main GUI?
2. Shortcuts for the system-tray context menu?
3. Or are we thinking of a shortcut that works anywhere on the desktop.

In the main GUI, the arrow keys act for the last slider control that was clicked (as does the mouse wheel).  So if you click on the brightness, from then on, the arrow keys up/down, left/right, mouse-wheel, should alter the brightness (at least that's true for my KDE desktop).

In respect to 1, Perhaps a shortcut for choosing which slider should be active might work.

I would have to investigate 2 or 3 (3 seems doubtful).

**Comment by digitaltrails** [comment]
Shortcuts in the context menu.

The Qt code for setting up shortcuts sets them up, but when the application is running in KDE or GNOME they don't work.  Not even after calling setShotcutVisibleInContextMenu(True).  

At least in KDE, the shortcuts are listed on the right of the menu, they just don't work.  GNOME doesn't even show the shortcuts as being available.

A special case is the system tray under KDE (but not GNOME).  When the context menu is brought up,  the first letter of each menu item already acts as a shortcut (whether I want it to or not).  For example, in the tray context menu, if I press P, the Presets dialog will popup.  This does means that, under KDE, if each preset is given a unique starting letter, that this is one way to create a shortcut for each preset (for example use 1,2,3,4 as the first letter in each preset name).  But these "default" shortcuts do not work if the same context menu is pulled up via the right-mouse in the application.

I noticed that some shortcuts advertised by other KDE applications in the KDE tray also do not work - so maybe this is a bigger issue, or something specific to my settings. 

Anyway that's the  sorry state of affairs of context menu shortcuts pending more info.

**Comment by digitaltrails** [comment]
I pondering the issue of shortcuts for the main control panel.  

For example, it would be nice if B and Shift-B would control the brightness.  But what if there are controls for more than one monitor, for example, one of my monitors has a huge brightness range, so B altering the brightness of both is not appropriate. Maybe B could jump from one monitor's brightness-control to the next, and then the arrows could be used for adjustment.

**Comment by digitaltrails** [comment]
See [https://stackoverflow.com/questions/23388754/two-shortcuts-for-one-action](https://stackoverflow.com/questions/23388754/two-shortcuts-for-one-action)

So an application wide shortcut is possible by calling:

```
action.setShortcutContext(Qt.ApplicationShortcut)
```

Other kinds of shortcuts apparently don't work, which is probably why I had no luck before.


So I can get shortcuts to work in the menu by following the advice from the above.  **BUT** they don't always work as expected.  

- They will work if the mouse is focused in the application.  
- They will work from the system-tray menu if the system-tray was clicked to restore the application **and the application has focus**.
- They do nothing if the menu is brought up in the system tray without first restoring the application and giving it focus.

I suppose a consistent way to proceed is to have no shortcuts in the system tray, only have shortcuts in the main application.  That's a bit of a snag, because the menu is a common object shared by the application and the tray - so the menu would require duplicating.

Maybe I can bind shortcuts to windows rather than menus.  Then they wouldn't be seen in the menu, so it wouldn't be as confusing.  But then they would not be self-documented (except where bound to buttons).

**Comment by digitaltrails** [comment]
![image](https://github.com/digitaltrails/vdu_controls/assets/5510901/d7d02437-5319-477c-9950-497e9cc5cc64)

**Comment by digitaltrails** [comment]
**Opinions wanted...**

I've duplicated the in-application _Context/Hamburger_ menu and the and and _System-Tray Right-Mouse_ menu:
  * The in-application context-menu/hamburger menu has shortcuts.
  * The system-tray right-mouse-menu does not have shortcuts.  This is because when the system tray right-mouse menu is visible, the shortcuts don't work!  **This appears to be a hard limitation within the Qt framework for KDE and gnome (gnome actually hides the system-tray shortcuts without me having to do anything).**

When ever the user opens the system-tray right-mouse-menu, the application has to copy the tray menu content over from the application context/hamburger menu. This seems to work OK.

This is a bit ugly/inconsistent, I'm not sure if I should release it.  **I would welcome opinions.**

![image](https://github.com/digitaltrails/vdu_controls/assets/5510901/b01d114a-00ce-4078-9147-9ab995bdeb1a)

**Comment by digitaltrails** [comment]
**Notes on how each desktop treats tray right-mouse menu shortcuts:**

* **KDE/Plasma:** for native KDE/Plasma tray apps, the right-mouse menu's right-margin advertised shortcuts don't work. For example, in the volume tray app, Alt+D or S is supposed to enter settings, neither works.  
  * For KDE/Plasma native systray apps, although the advertised shortcuts don't work, holding down **Alt** causes the first letter of each menu option to be underlined - indicating they are shortcuts, and they work! **This separate shortcut mechanism overrides the advertised shortcuts.** 
  * Alt for shortcuts doesn't happen for Qt apps (such as vdu_controls), it's special to native KDE/Plasma apps.
* **Xfce** and **Gnome** an application's shortcut advertising on the right-mouse tray-menu is censored and doesn't show in the right margin. No shortcuts work. Xfce and Gnome native-app tray right-mouse menus don't appear to have any shortcut mechanism.

The lack of operative shortcuts in the tray right-mouse menu is quite common on Linux. KDE native apps have a weird override of the app declared shortcuts in favour of **Alt+_first-letter-of-menu-item_**.  Xfce and gnome, don't support shortcuts for these menus, and they censor any declared shortcuts so the user won't be confused. 

**Conclusions:**
* Implementing shortcuts in the manner [previously described](https://github.com/digitaltrails/vdu_controls/issues/13#issuecomment-1675708870) would result in a _normal_ level of inconsistency for a Linux application.  
* I will check in the necessary changes.
* Whether the KDE/Plasma native Alt mechanism can be engaged for Qt apps needs to be investigated.

**Comment by digitaltrails** [comment]
**_Arggggg!!_**

There are two shortcut mechanisms.  The one I was using works as described above.  The second one is leveraged off of holding down **Alt**.  **In KDE/Plasma this second kind of shortcut mechanism works both in the app and the system-tray.** 

No joy for gnome or xfce though - the shortcuts only work in the application, not the tray.

So I can junk the code I've written, and use this second mechanism (maybe).

**Comment by digitaltrails** [comment]
On the second type of Alt-based shortcut, the system-tray and application disambiguate menu entries differently - which is a problem because they both auto-assign them.  So I would need to duplicate one of the disambiguation algorithms and allocate preset shortcuts accordly.  This is needed because **Alt-_number_** doesn't work, so presets are going to have to be **Alt-_letter_** which might clash with already used letters.

**Comment by digitaltrails** [comment]
I implemented shortcuts unified under the **Alt-_letter_** system in commit b968054.

**Application Context-Menu**
In the application internal context-menu for KDE/Plasma, gnome and xfce, holding down **Alt** within the application-menu will underline what shortcuts have been allocated. In all desktops, the shortcuts are only revealed in the menu when the Alt key is help down (for reasons of consistency).

**System-Tray right-mouse Menu**
For the system-tray right-mouse menu: in KDE/Plasma holding down Alt will reveal the same shortcuts as the Application-Menu and they work; in gnome/xfce no menu shortcuts are available from the tray menu because those desktops don't provide that functionality.

**In the application window**
In the application window for KDE/Plasma, gnome, and xfce, the shortcuts listed in the menus can be used in the window without bringing up a menu.

**The allocation of shortcuts to Presets**
Shortcuts for Presets are allocated after the basic menu actions.  Only letters (A-Z) are available (I could not get numbers 0..9 to work). If the app runs out of letters then some Presets won't have shortcuts.  Some presets may need to be renamed to enable a shortcut to be allocated, for example a Preset called H conflicts with Alt+H for help.

** Rant **
Something this basic in standards should not be so broken :-)
