### ISSUE TITLE
Min and max brightness vals for quirky monitors (custom mapping)

### ISSUE THREAD

**Issue by taprobane99** [digitaltrails/vdu_controls#17]
Is it possible to only allow a set range of values for quirky monitors.

For whatever reason my monitor has 59 as min brightness, 84 as max brightness. 58 and 85 put the monitor into a state where it cannot accept any input, the OSD is disabled, and can only be rescued by sending a valid brightness value.

So ideally I would like the values sent to only go from 59-84. And even better if this could be mapped to show 0-100 in the GUI slider.

I also know of other monitors with different value ranges, so this should be helpful for other users.

**Comment by digitaltrails** [comment]
What does ddcutil report as the maximum for the brightness VCP code?

`ddcutil --display 1 getvcp 10`

If it reports max value = 100, then yes this would have to be dealt with specially.  I'll start thinking about the nicest way to do this.

**Comment by digitaltrails** [comment]
I just pushed a change that adds the ability to add a range specification to the capabilities override section of the settings panel.  For example, to restrict the range for brightness, add the line `Values: min..max` to Feature 10 as can be seen in the attached screen shot:
![Screenshot_20220407_135830](https://user-images.githubusercontent.com/5510901/162105616-1a55c4f4-94e4-47ee-abd7-44a47bb20310.jpg)
e

**Comment by taprobane99** [comment]
It reports 100

Nice, that would definitely make the slider less dangerous for my monitor! I'm running the AUR package so not sure how to test it.

http://aur.archlinux.org/packages/vdu_controls

I guess the complete solution would to map these values to 0...100, so the onscreen slider always displays 0...100 but for quirky monitors the real values sent are scaled and integer rounded to e.g. 20...90. so 0-->20, 50-->55, 100-->90 in your example.

**Comment by digitaltrails** [comment]
> It reports 100
> 
> Nice, that would definitely make the slider less dangerous for my monitor! I'm running the AUR package so not sure how to test it.

Because you already have all the necessary dependencies installed, you could just download vdu_controls.py and then run it with python-3.  I'm not sure about arch, but python3 on my system is just python3:

`python3 vdu_controls.py` 

> 
> http://aur.archlinux.org/packages/vdu_controls

I'm not sure what triggers arch's process that picks up changes to vdu_controls from github.  I suspect if I make a new github release that might trigger it.  Over the next day or few I will document this new feature and make a release.  After that's done I'll wait a day or so and check the AUR link and see if it updates (I have no association with who ever setup the arch packaging).  

> 
> I guess the complete solution would to map these values to 0...100, so the onscreen slider always displays 0...100 but for quirky monitors the real values sent are scaled and integer rounded to e.g. 20...90. so 0-->20, 50-->55, 100-->90 in your example.

I'm not sure about that.  It might be better to show the true permitted value range.  In that way the user doesn't operate under any false assumptions.   The limits and values they see in vdu_controls are then the same as those that they might apply manually (via ddcutil).  The slider visual would be the way to tell whether the setting is at the max or min.

**Comment by digitaltrails** [comment]
[http://aur.archlinux.org/packages/vdu_controls](http://aur.archlinux.org/packages/vdu_controls) updated today after I created version 1.6.2 of vud_controls.

**Comment by taprobane99** [comment]
can confirm this works great for my monitor. thanks.

**Comment by digitaltrails** [comment]
> can confirm this works great for my monitor. thanks.

Thanks, that's good new.  I think it's quite a useful feature, thanks for suggesting it.
