### ISSUE TITLE
presets sorting

### ISSUE THREAD

**Issue by kupiqu** [digitaltrails/vdu_controls#26]
not sure how presets end up being sorted but it would be good to have a way to sort them manually (or alternatively according to e.g., brightness)

**Comment by digitaltrails** [comment]
Agreed, I'll look into it.

**Comment by digitaltrails** [comment]
> not sure how presets end up being sorted but it would be good to have a way to sort them manually (or alternatively according to e.g., brightness)

The current order is the natural directory (allocation) order.  This is the same as shown with `ls -f ~/.config/vdu_controls` - so it depends on the filesystem allocation of directory entries.  Which is not that useful.

**Comment by digitaltrails** [comment]
Possibilities:

- Default to alphabetical order - easy because it doesn't require reading the content of the files.
- Default to brightness order - only meaningful if brightness is the principle part of the preset - not useful for people who use presets functionally for "movies", "games", "photography", ...
- Default to creation order, corresponding to `ls -rt` which would be similar to now, but more comprehensible to a human.
- Have a default, but allow reordering by some means - drag and drop if it's easy to achieve.  

I think creation order with the ability to reorder might be the most versatile approach:  

- The manual ordering could be accomplished with minimal change to the preset_controller by adding ordering into the existing file names, for example: `Preset_Sunny.conf` might become `Preset_001_Sunny.conf`. 
- On first run of the new version it could assign numbers based on the existing "-f" ordering so that the old/existing ordering is not perturbed. 
- On reordering, files would just change name, so `Preset_001_Sunny.conf` to `Preset_002_Sunny.conf`
- It would be good to come up with an approach that doesn't require all files to be renamed when the order is altered.  Maybe `Preset_100_Sunny.conf`, or some other scheme that leaves gaps with an algorithm that tries to plug gaps an minimise renames where possible.

...

**Comment by kupiqu** [comment]
What about not changing the name of the preset files that would be messy, but just saving the sorted list in a vdu_control config file?

Wondering if it would be easy to generalize the sorting according to {alphabetical, date of creation, numerical features like contrast and brightness (are there others?), and then manually for the rest of use cases}

**Comment by digitaltrails** [comment]
> What about not changing the name of the preset files that would be messy, but just saving the sorted list in a vdu_control config file?
> 
You're right that might be a good approach and I had thought about it.  But I'd prefer to avoid duplicating data that might get out of alignment. For example, what say one or more of the files is manually deleted/renamed, now the main config file is out of alignment, but perhaps this not a major issue to check.   I haven't decided at a final approach at this point, but I  would like to support easy manual editing of config files, so I'm hesitant to require some cross editing of files.  One measure will be to see how ugly the coding gets - python often offers surprising solutions that make things simpler than they seem.

> Wondering if it would be easy to generalize the sorting according to {alphabetical, date of creation, numerical features like contrast/brightness (are there others?), and then manually for the rest of use cases}

That might be nice, but it would also be a large amount of work, each file would have to be loaded to find the relevant values, some kind of GUI interface that allows keys, sub-keys to be picked would need to be written.  Also, some presets might not include some/all key values (presets need not include all fields) - so how to sort by brightness if brightness isn't in the preset. So I thought perhaps, just allow drag-and-drop reordering, and folk could apply whatever they want manually.

**Comment by kupiqu** [comment]
Yeah, good points. Drag-and-drop would be great! I hope it's not too hard technically.

**Comment by digitaltrails** [comment]
> Yeah, good points. Drag-and-drop would be great! I hope it's not too hard technically.

Yes, let's hope not.  I can fall back to something like up/down buttons in the preset-UI to move a preset accordingly.

**Comment by digitaltrails** [comment]
I've pushed some changes that implement this functionality.  Rather than drag and drop, it was easier to add a couple of buttons for up/down.  In the end I have written the order to a file, not the main vdu_controls.conf, but to a separate Order_Presets.conf which just contains one line of CSV - again, this was the easiest approach.

I'm going to see how this gos on my desktop for a few days.  I will most likely make a new release after that.

Feedback is welcome.

**Comment by kupiqu** [comment]
> I've pushed some changes that implement this functionality. Rather than drag and drop, it was easier to add a couple of buttons for up/down. In the end I have written the order to a file, not the main vdu_controls.conf, but to a separate Order_Presets.conf which just contains one line of CSV - again, this was the easiest approach.
> 
> I'm going to see how this goes on my desktop for a few days. I will most likely make a new release after that.
> 
> Feedback is welcome.

Sounds great! Unfortunately I won't be able to test until version 1.7.2 is released as I'm using the rpm package in my system

**Comment by digitaltrails** [comment]
The changes to the UI:

![Screenshot_20221007_163046](https://user-images.githubusercontent.com/5510901/194462491-ba385abf-2fa4-4038-b8aa-62602a84f797.png)
