### ISSUE TITLE
[feature] Automatic adjustments based on sunrise/sunset

### ISSUE THREAD

**Issue by Jakeler** [digitaltrails/vdu_controls#28]
The idea is automatically switch profiles based on the natural background brightness.
Ideally with smooth transitions, so small steps to reach to target set in the profile.

Sunrise+sunset times can be calculated from the location for example with the [astral module](https://astral.readthedocs.io/en/latest/).
Location in lat:long coordinates could be either set manually or obtained via a location service that checks the IP etc.

A toggle switch for the automatic/manual selection in the tray menu would be useful.

Example from KDE:
![grafik](https://user-images.githubusercontent.com/13378765/196799662-24b23b48-3702-41cc-8a71-76577c4e7cf2.png)
It does not allow to change the brightness, but is otherwise very well made. 
Also adjusted color temperature might be possible via ddc:
```
VCP code 0C: Color temperature request
   Specifies a color temperature (degrees Kelvin)
   MCCS versions: 2.0, 2.1, 3.0, 2.2
   ddcutil feature subsets: COLOR
   Attributes: Read Write, Continuous (complex)
```
Should produce a better result than the software filters (which reduce color depth). 
Most important is the brightness I think though.

**Comment by digitaltrails** [comment]
> The idea is automatically switch profiles based on the natural background brightness. Ideally with smooth transitions, so small steps to reach to target set in the profile.
> 
> Sunrise+sunset times can be calculated from the location for example with the [astral module](https://astral.readthedocs.io/en/latest/). Location in lat:long coordinates could be either set manually or obtained via a location service that checks the IP etc.
> 
> A toggle switch for the automatic/manual selection in the tray menu would be useful.

I agree this might be useful.  

I had previously investigated the availability of libraries to do these calculations and had located some.  The question was then whether to create a dependency on them or fold the code in.  I guess a non-mandatory run-time dependency would be best because I'm not sure any of these libraries are included by all distros.  I also considered folding in the required code, but the little "script" is getting quite big.

Another thought I had was to pull weather and daylight-hour info from the web and use a python equivalent to `wget -qO- wttr.in` or more specifically formatted results such as `wget -qO- 'wttr.in/?format=%D+%S+%z+%s+%d'` - this would then only require http and would likely work anywhere that there is internet access.  This might then also allow brightness levels to be keyed to the prevailing local weather conditions.   What do you think of that approach?

> 
> Example from KDE: ![grafik](https://user-images.githubusercontent.com/13378765/196799662-24b23b48-3702-41cc-8a71-76577c4e7cf2.png) It does not allow to change the brightness, but is otherwise very well made. Also adjusted color temperature might be possible via ddc:
> 
> ```
> VCP code 0C: Color temperature request
>    Specifies a color temperature (degrees Kelvin)
>    MCCS versions: 2.0, 2.1, 3.0, 2.2
>    ddcutil feature subsets: COLOR
>    Attributes: Read Write, Continuous (complex)
> ```
> 
> Should produce a better result than the software filters (which reduce color depth). Most important is the brightness I think though.

I was a bit worried about making controls available that might not exist in a monitors physically provided controls.  My main concern was that this might allow people to paint themselves into a corner, do something irreversible, or even perhaps brick their hardware.  So I've been quite conservative in what I've supported out of the box.  For example, my LG monitor seems to support heaps of codes that don't feature on its physical menus - are they safe to use?   I can probably expand out what is safe by doing a bit of research into what is considered safe for ddcutil and other such utilities.

**Comment by digitaltrails** [comment]
> ```
> VCP code 0C: Color temperature request
>    Specifies a color temperature (degrees Kelvin)
>    MCCS versions: 2.0, 2.1, 3.0, 2.2
>    ddcutil feature subsets: COLOR
>    Attributes: Read Write, Continuous (complex)
> ```
> 
> Should produce a better result than the software filters (which reduce color depth).
> Most important is the brightness I think though.

As a test, in my local source, just added 0C to the list of enabled VCP codes.  My old HP monitor claims to support it.  But I immediately struck a problem.  The VCP code is supposed to be continuous-complex, but the monitor actually offers three hard choices and one where each of RGB can be varied.  However, changing the continuous value has an unpredictable effect and only by using the monitors actual controls can I get back to any of the three fixed values.  The notes provided for ddcutil don't look promising - search in-page for temperature in [https://www.ddcutil.com/monitor_notes/](https://www.ddcutil.com/monitor_notes/).  It seems the CNC value may be interpreted differently by different monitors.

I suspect this code might not be a good one to support.  The results may just be too unpredictable and confusing. Perhaps for specific monitors.  Perhaps with some big first-time-use popup warning.  I another problem would be that I don't have a monitor that supports the code, so I have no means to test it.

**Comment by digitaltrails** [comment]
Jotting down more thoughts - before I forget them.

It might be relatively easy to have the code periodically wake and use python to retrieve 

```wttr.in?format="dawn=%D,dusk=%d,weather=%C"```

Which would result in a string such as: `"dawn=05:56:01,dusk=20:16:17,weather=Partly cloudy"`

And then: 
1. figure out if it is after dawn or after dusk; 
2. attempt to match a preset such as `Preset_After-Dawn.conf`, `Preset_After-Dusk.conf`, or `Preset_After-Dawn_Partly-cloudy.conf`.

I suspect what would actually be good is to offset the cut-over.  Dawn and dusk are pretty dark in some latitudes, and the length of dawn/dusk can vary considerably at different times of the year.  Then there is the issue that some folk live in dark valleys and others face the northern or southern sky.   So what might really be needed is some complex rules in the preset such as if dawn+2-hours and partly-cloudy.  

As I mentioned in the man-page, I implemented signals so folk could write complex external scripts that took into account their own circumstances.   I have considered bundling one or more such scripts and may do so at some point in the future. It would be nice if they could be configured from with the existing GUI - perhaps they could conform to a vdu_control preset-trigger plugin interface.

I think there is also a new Linux standard webcam interface in the works.  If that becomes standardised and winds up with a widely supported python library, then perhaps vdu_controls or a plugin could measure light levels directly, but cheap webcams often do autogain, so measuring with some cameras may not be so easy.

**Comment by digitaltrails** [comment]
I now have an 70 line self-contained function that, given the time of day, latitude and longitude, returns as estimate of the solar zenith/elevation in degrees.  Maybe daytime could be defined as beginning when the sun reaches a certain angle of elevation and ending when it declines below a second angle of elevation.  This would solve the issue that dawn and dusk are often too dark to be treated as daytime.  It also addresses the issue of daylight varying by latitude and time of year - it would work for users with the arctic circle!  

User defined solar elevations might also be a practical way to take into account of the orientation of the working environment, but perhaps that might also require azimuth.

Using sun elevation does not solve the issue of the weather. However the sun elevation could be used to determine "daytime". 
Daytime could be the period when presets are applied according to the local weather.

I need to think about if/how to bring this together in a simple/useful way for users.

**Comment by digitaltrails** [comment]
An implementation of solar azimuth/elevation triggers is mostly complete.  Testing is going to take some time.

A screen grab of the Preset-UI changes:
![Screenshot_20221030_solar_elevations_80](https://user-images.githubusercontent.com/5510901/198862841-911ef7a0-ffd1-4b5d-bc9a-daa9e5721dcc.png)

One limitation,  if a monitor is switched off or in power saving the trigger may not act, or it may block in an error dialog, in which case dismissing the dialog may result in some of the trigger action completing.  In these circumstances, exactly what happens may also depend on how many monitors are connected.  Actual use might help resolve how best to handle this situation.

There also seems to be a slight rounding error visible in the screen grab (9:49 versus 9:50).

**Comment by digitaltrails** [comment]
I still have to look at transitioning gradually to the desired brightness (and maybe contrast) - which should probably be optional, so perhaps another preset setting.

**Comment by digitaltrails** [comment]
I've released [v1.8.0](https://github.com/digitaltrails/vdu_controls/releases/tag/v1.8.0) which covers much of the requested functionality.  I have not yet addressed the gradual transitions feature, but will look into it for a future release (the amount of change in v1.8.0 was getting a bit unwieldy) . I will close this issue and initiate a new one for a feature that transitions values. 

Thank you for raising this issue.

**Comment by Jakeler** [comment]
Thank you so much! Nice offline implementation, I used it today and it worked perfectly.

Incorporating weather data is also a interesting idea. Could imagine though that setting up the profiles for different conditions would be quite complex. Rainy is sometimes still bright, can be even slightly sunny at the same time. Cloudy weather can be darker, even without rain, etc... Maybe calculating from a more direct measurement like the `cloudcover` percentage provided by wttr.in would work.
For me personally tuning by hand on unusual conditions is fine, as the auto switching based on sun elevation every day is already a huge help.

**Comment by digitaltrails** [comment]
> Thank you so much! Nice offline implementation, I used it today and it worked perfectly.

Thanks for the feedback.  It's good to hear it's working somewhere else in the world.  I tested the calculations by setting the  timezone and location, but I was worried I had overlooked something. 

> Incorporating weather data is also a interesting idea. Could imagine though that setting up the profiles for different conditions would be quite complex. Rainy is sometimes still bright, can be even slightly sunny at the same time. Cloudy weather can be darker, even without rain, etc... Maybe calculating from a more direct measurement like the `cloudcover` percentage provided by wttr.in would work. 

Yes, I have been playing a a bit with wttr.in and had noted `cloudcover` (and `visibility`) in the json data.  

> For me personally tuning by hand on unusual conditions is fine, as the auto switching based on sun elevation every day is already a huge help.

I've found it works well for me too.  When the auto switch turns out to be wrong for the circumstances, it serves as a useful reminder to consider a manual adjustment.  It's great to not have to remember to do anything first thing in the morning or later in the evening.

I also like that the solution is offline, so I don't have to depend on polling some site, which is exactly what I'd need to do with wttr.in.  

I'm not yet convinced using wttr.in is a huge win, especially when the weather data may not be 100% current.  I may knock up something rough to get the feel of it.

The other direction I could go in, is to use open hardware to measure the light level. Perhaps a service running on a raspberry pi or arduino.

Thanks again for bring this up, otherwise I might not have got around to doing anything concrete for ages.
