### ISSUE TITLE
Can't install on Ubuntu/Pop_OS?

### ISSUE THREAD

**Issue by roadsign** [digitaltrails/vdu_controls#4]
Hi,

This is what I'm getting when trying to install:

> lucasr@pop-os:~/src/vdu_controls$ sudo python3 vdu_controls.py --install
[sudo] password for lucasr: 
ERROR: No desktop directory is present:/root/.local/share/applications Cannot proceed - is this a non-standard desktop?

The command `ddcutil` only works when run as sudo. The same applies for `vdu_controls.py`

I would like to install the script to my user. What is the equivalent in this distro?

Thank you!

**Comment by digitaltrails** [comment]
On Saturday 18 September 2021, Lucas Rosalino wrote:
> Hi,
> 
> This is what I'm getting when trying to install:
> 
> > ***@***.***:~/src/vdu_controls$ sudo python3 vdu_controls.py --install
> [sudo] password for lucasr: 
> ERROR: No desktop directory is present:/root/.local/share/applications Cannot proceed - is this a non-standard desktop?
> 
> The command `ddcutil` only works when run as sudo. The same applies for `vdu_controls.py`
> 
> I would like to install the script to my user. What is the equivalent in this distro?
> 
> Thank you!
> 
Hi,

The key is to get ddcutils working first.

Vdu_controls --install is not intended for use by the root user, the install option is only to 
be run by a normal user for installation into $HOME for that user.  Once ddcutil runs 
correctly, the vdu_controls should just work.

ddcutil requires access to the i2c bus via the kernel module i2c-dev.  Different distributions 
have different ways to grant normal users the required access.  I've not had a huge
amount of luck on searching out how ubuntu works in this respect (I've never used it), but 
the answer-3 to this question sounds plausible:

https://askubuntu.com/questions/1273700/enable-spi-and-i2c-on-ubuntu-20-04-raspberry-pi

That answer appears to agree with the help available at www.ddcutil.com:

https://www.ddcutil.com/i2c_permissions/

Note that the bottom of that page also has a suggested simpler way to do a quick 
test by setting the i2c devices to be read/write for all users.

I must confess I'm now puzzled about how things "just-work" on OpenSUSE which
doesn't have a i2c group, I'll have to find out.

Cheers,
Michael

**Comment by digitaltrails** [comment]
In respect to getting ddcutil working on ubuntu, it would be good to first follow the quick test described at [https://www.ddcutil.com/i2c_permissions/](https://www.ddcutil.com/i2c_permissions/), the steps would be:

1. Temporarily grant rw to everyone: **sudo chmod a+rw /dev/i2c-***
2. See if ddcutils works in the normal users account:  **ddcutils detect**
3. See if vdu_controls now works in the normal users account:  **python  vdu_controls.py**

If this works, then following the longer series of steps detailed by the links in the previous comment would be the key to getting permissions set permanently.

BTW, OpenSUSE applies the necessary permissions dynamically to that specific user. OpenSUSE uses systemd-logind to add ACL's (see  man setfacl) for the session user on login, and takes them away on logout.  udevadm is also involved.  So OpenSUSE is quite different, it's permissions are more restrictive and automatically applied on login, so I did not have to do anything to permission on my desktop.

**Comment by roadsign** [comment]
Thank you for the explanation.

I've managed to make ddcutil run correctly. I've followed the page https://www.ddcutil.com/i2c_permissions/ and the commands below were sufficient:

```
# The group i2c already existed
sudo usermod your-user-name -aG i2c
sudo cp /usr/share/ddcutil/data/45-ddcutil-i2c.rules /etc/udev/rules.d
```

Now both ddcutil and vdu_controls work in the normal users account.

Here's what I'm getting when trying to install vdu_controls after that:

> lucasr@pop-os:~$ python3 ~/src/vdu_controls/vdu_controls.py --install
ERROR: No desktop bin directory is present:/home/lucasr/bin Cannot proceed - is this a non-standard desktop?

Is there supposed to be a bin folder for user accounts? (or equivalent in Ubuntu/Pop_OS?)

**Comment by digitaltrails** [comment]
> Thank you for the explanation.
> 
> I've managed to make ddcutil run correctly. I've followed the page https://www.ddcutil.com/i2c_permissions/ and the commands below were sufficient:
> 
> ```
> # The group i2c already existed
> sudo usermod your-user-name -aG i2c
> sudo cp /usr/share/ddcutil/data/45-ddcutil-i2c.rules /etc/udev/rules.d
> ```
> 
> Now both ddcutil and vdu_controls work in the normal users account.

Good news.

> 
> Here's what I'm getting when trying to install vdu_controls after that:
> 
> > $ python3 ~/src/vdu_controls/vdu_controls.py --install
> > ERROR: No desktop bin directory is present:/home/lucasr/bin Cannot proceed - is this a non-standard desktop?
> 
> Is there supposed to be a bin folder for user accounts? (or equivalent in Ubuntu/Pop_OS?)

From what I've googled about ubuntu, if you create /home/lucasr/bin, then it will be added to the path on future logins.  So as lucasr your could 
```
   $ mkdir /home/lucasr/bin
   $ python3 ~/src/vdu_controls/vdu_controls.py --install
```
Then logout/login and see it it's on your path.  If that failed to work, you would need to add that folder to the PATH, which is likely an ubuntu FAQ.

If /home/lucasr/.local/share/applications/ does not exist, you might encounter problems with the next step that creates a desktop file to put vdu_controls in the "start menu".  You might need to create that folder too:
```
  $ mkdir -p /home/lucasr/.local/share/applications
```
If ubuntu obeys the same standards as KDE/gnome, installing a desktop file in that folder should work.  Otherwise it's not completely necessary to install vdu_controls in this way.  You could just run it as you are now.  The necessary command could be put into a bash script, the bash script could be added to the startup menu via whatever process ubuntu provides to do that.

**Comment by roadsign** [comment]
The start menu path already existed, so creating the Desktop bin folder was enough. I'll read more about that.

Thank you!

**Comment by digitaltrails** [comment]
> The start menu path already existed, so creating the Desktop bin folder was enough. I'll read more about that.
> 
> Thank you!

That's good news, thanks for helping out with this.  

I will change the install option to create $HOME/bin if it's not already there.  I had originally coded it that way, but then worried that if $HOME/bin did not exist, it might indicate a distro is a bit unusual.  Now that I know that ubuntu will add a newly created $HOME/bin to the PATH, I'm confident that creating the directory is the right approach.  As ubuntu is quite popular, I may as well remove this hurdle.

It makes sense that $HOME/.local/share/applications already exists, I think that's standard for any of the modern desktops that  support the concept of some kind of application menu or desktop icons.

Long term I may think about packaging vdu_controls for installation for use by all users on a machine.  But before that, I think I need to think more about configuration files in order to avoid having to configure arguments like ``--hide contrast`` in the desktop file.

**Comment by digitaltrails** [comment]
Commited 8aeeb5c that will create ``$HOME/bin`` if it doesn't exist.
