### ISSUE TITLE
vdu_controls crashes if ddcutil not found

### ISSUE THREAD

**Issue by rockowitz** [digitaltrails/vdu_controls#48]
If vdu_controls does not detect ddcutil, it can crash in various ways.  You probably want to put up a message that ddcutil must be in the users path and exit immediately after the message is read.

**Comment by digitaltrails** [comment]
Something I'd overlooked, thanks for pointing it out. I hope to have it covered before the next release.

**Comment by digitaltrails** [comment]
This used to be handled, but layering on other error handling options masked it. Fixed at startup/initialisation (might still be problem if ddcutil goes missing later).

**Comment by rockowitz** [comment]
I just tested running _vdu_controls without ddcutil installed. After clicking OK on the "No controllable monitors found." message box, vdu_controls minimizes to the system tray.  When I open vdu_controls, it's possible to click on the refresh button, causing a segfault.   I suggest that if the error message on the initial dialog is "No such file or directory 'ddcutil'" vdu_controls should terminate instead of minimizing to the system tray after the user clicks OK.

**Comment by digitaltrails** [comment]
I'll nail it down yet.

**Comment by digitaltrails** [comment]
I would like the user to always be able to get into the GUI proper.  This is just in case a problem is caused by some setting change they've made - they should always be able to get to the settings GUI.  

It's a relatively trivial change to get refresh to pick up ddcutil becoming available.  It's quite similar to a monitor becoming available.
