### ISSUE TITLE
Panel Icon - Dark/Light-Mode

### ISSUE THREAD

**Issue by abil76** [digitaltrails/vdu_controls#66]
Dear developers,
I really like your really very useful app and thank you for your work. But I'm still annoyed about one little thing.
Why do they change their panel icon so often? Why is the icon hardcoded? And why aren't monochrome icons offered for light and dark modes? As a Linux user with a nice monochrome panel, your icon is inappropriate and strange. Every week after an update I have to adjust my icons. Here is a photo of my desktop where I customized your icon. 
Best regards and thank you for your great work!

![image](https://github.com/digitaltrails/vdu_controls/assets/46962320/1e5772e5-2d68-4411-abe9-ac12ba51b366)

**Comment by digitaltrails** [comment]
> Dear developers,
> I really like your really very useful app and thank you for your work. 
Thanks.

> But I'm still annoyed about one little thing.
> Why do they change their panel icon so often? 

The panel icon embeds the icon for the current Preset, the indicator Preset transitioning (green flashing dot), and the indicator for auto-brightness/lux adjustment (steady orange dot when enabled).  So it is regenerated to incorporate these other indicators, as can be seen here:

![Screenshot_20231021_131353](https://github.com/digitaltrails/vdu_controls/assets/5510901/c7abc118-dec2-480e-b691-be4c790afdf5)

![Screenshot_20231021_133143](https://github.com/digitaltrails/vdu_controls/assets/5510901/64f0603c-9ab7-4c36-81ee-fd703c811600)


A slowly transitioning Preset would flash a green indicator, similar to the orange one, on the left side of the icon until the transitioning finishes. If Presets don't have any transitions set, you'd never see the green indicator.  Similarly, if you don't enable lux-metering, no orange indicator will be visible.

> Why is the icon hardcoded? 

An attempt is made to load the basis for the icon from `/usr/share/icons/hicolor/256x256/apps/vdu_controls.png`, if that fails an embedded jpeg is used instead.  If it was desired, code could be added to try loading it from `$HOME/.config/vdu_controls/vdu_controls.png` first.  The reason it's a PNG is the file is actually the source for the splash-screen and the icon is just a shrunken version of that.

> And why aren't monochrome icons offered for light and dark modes? As a Linux user with a nice monochrome panel, your icon is inappropriate and strange. Every week after an update I have to adjust my icons. Here is a photo of my desktop where I customized your icon.

Mainly because no one has asked for such a feature.  I have not used a monochrome desktop since the 1990s, for a while I used an hardware "X-Terminal"/X-Server with a monochrome CRT, but not since, so it's not on my personal radar :-)

Some aspects of the icon used to be modified for light and dark modes, but that caused problems with the visibility of the overlays.  For a monochrome icon to work well with the overlaid Preset symbols/abbreviations, it should probably always have a lighter color screen.

> Best regards and thank you for your great work!

The easiest thing to do would be to an extra search path for the icon: `$HOME/.config/vdu_controls/vdu_controls.png`.  The you'd be free to make it work with your own designs for Preset icons.

**Comment by abil76** [comment]
I used incorrect definitions regarding the terms “monochrome” and “panel”. By “Monochrome” I actually meant black/white icons and by “Panel” I meant the top bar of a desktop environment like KDE, Gnome or XFCE. I apologize for the misunderstanding.

> The easiest thing to do would be to an extra search path for the icon: `$HOME/.config/vdu_controls/vdu_controls.png`. The you'd be free to make it work with your own designs for Preset icons.

Implementing an additional search path would be great! This would solve the customizing problem. I would like to thank you for the very detailed and quick answer.

I wish you much success with your great app, which I use every day. It has a great health effect on my eyes and makes my work and the work of many other people in front of the monitor easier.

**Comment by digitaltrails** [comment]
> I used incorrect definitions regarding the terms “monochrome” and “panel”. By “Monochrome” I actually meant black/white icons and by “Panel” I meant the top bar of a desktop environment like KDE, Gnome or XFCE. I apologize for the misunderstanding.

I think I understood this correctly.  I experimented with adding a second embedded monochrome app icon.  It's very easy to add boolean options, so I added a monochrome tray option to enable it:

![image](https://github.com/digitaltrails/vdu_controls/assets/5510901/294be03b-62ad-48c8-88c1-2f6939e8fd68)

It's themed, and adjusts to dark/light theme changes immediately in KDE:

![Screenshot_20231021_173459](https://github.com/digitaltrails/vdu_controls/assets/5510901/2e8162aa-e4fe-414e-a5da-e4b9baf85e7e)

The orange auto-lux indicator would still appear if you turned auto on:

![Screenshot_20231021_174416](https://github.com/digitaltrails/vdu_controls/assets/5510901/f410856c-f9f0-42c1-b1f4-a275fbd6173a)

It was a little tricky getting a icon that overlaps nicely with the icons/abbreviations for presets, but I got there in the end.

> 
> > The easiest thing to do would be to an extra search path for the icon: `$HOME/.config/vdu_controls/vdu_controls.png`. The you'd be free to make it work with your own designs for Preset icons.
> 
> Implementing an additional search path would be great! This would solve the customizing problem. I would like to thank you for the very detailed and quick answer.

If you would prefer to create your own icon, I can look into that.  Otherwise I will tidy it up and push it - probably tomorrow local time.

> I wish you much success with your great app, which I use every day. It has a great health effect on my eyes and makes my work and the work of many other people in front of the monitor easier.

Thanks. I only wrote it because I bought a new monitor.  I soon discovered back-lights are a lot brighter now. That's great during the day, but the monitor gives me sunburn at night.  So I thought I share the little script, now it's not so little :-)

I glad it's having a positive effect in your workplace.  It's nice to get some feedback.

**Comment by digitaltrails** [comment]
I think there does need to be support for a user provided icon because I can't figure out how to deal with a desktop that is only dark themed inside the panel, an example being the KDE Breeze-Twilight theme.

**Comment by digitaltrails** [comment]
OK, I've check in code that offers both routes.  Either switch on *monochrome tray* in settings, or supply a $HOME/.config/vdu_controls/app_icon.svg file.

There are a three suitable svg files in [icons](https://github.com/digitaltrails/vdu_controls/tree/ca75a828c95f2479aa3f157e44a188d86ef2ae8d/icons) one called 

1. `app_icon.svg` (for light themes)
2. `app_icon_white.svg` (for dark themes)
3. `app_icon_white_middle.svg` (for dark-panel-light-desktop themes)

Switching on *monochrome tray* works well for full on light or dark screen desktops.

A custom icon kind of works best for dark-panel-on-light-desktop themes.  But if falls short when overlaying info onto the icon because the light-desktop forces dark overlay.  This can be worked around by using a icon with a white middle, such as `app_icon_white_middle.svg`.

I need to think about how to handle that. Maybe a metadata hint in the svg file might work.  But implementing that blows the current simplistic theme handling code out of the water.

The advantage of the original color icon is it steps around the whole business.

**Comment by digitaltrails** [comment]
Idea: Inspect the rendered icon to find out if the middle is dark or light * is_icon_dark(icon: QIcon) - use appropriate overlays.

**Comment by abil76** [comment]
All new icons look really great! Both the light and dark modes look very good. As a long-time Arch KDE Plasma user, I find the icons ideal for a plasma system tray.

![image](https://github.com/digitaltrails/vdu_controls/assets/46962320/0be8d201-4b22-4341-93ea-b8f094cb0560)
![image](https://github.com/digitaltrails/vdu_controls/assets/46962320/4ebaa334-88e0-4116-882c-96eba45ea3ef)
![image](https://github.com/digitaltrails/vdu_controls/assets/46962320/2a93cbf5-903d-4433-b1ae-785f010afdfa)

> I think there does need to be support for a user provided icon because I can't figure out how to deal with a desktop that is only dark themed inside the panel, but light-themed everywhere else, an example being the KDE Breeze-Twilight theme. 
OK, I've check in code that offers both routes. Either switch on monochrome tray in settings, or supply a $HOME/.config/vdu_controls/app_icon.svg file.

It's really great that you found a solution for this too, because I have a desktop theme exactly like this. My panel icons are white, my application icons are dark, like Breeze Twilight.

And it's particularly good that the icons are in svg format, because svg icons look much better in KDE Plasma panels. PNG images are slightly distorted in color.

I'm already looking forward to the next update! Thank you very much for your effort.

**Comment by digitaltrails** [comment]
> It's really great that you found a solution for this too, because I have a desktop theme exactly like this. My panel icons are white, my application icons are dark, like Breeze Twilight.
> 
> And it's particularly good that the icons are in svg format, because svg icons look much better in KDE Plasma panels. PNG images are slightly distorted in color.
> 
> I'm already looking forward to the next update! Thank you very much for your effort.

This morning I decided to bit the bullet and introduce another setting *mono-light-tray* to go along side *monochrome-tray*.  This will enable the code to do the right thing for "Twilight-like" desktops without the user needing to manually create any icons.  

I thought about having one setting, a combo-box, but the settings code doesn't support that, rather than doing a lot of work I'll just use two boolean settings.

I'm also going to leave in the code for a custom icon - just in case someone has a really wacky theme and they need an override.

All coded, seems to work, but still testing.

**Comment by abil76** [comment]
> I thought about having one setting, a combo-box, but the settings code doesn't support that, rather than doing a lot of work I'll just use two boolean settings.

Exactly, you don't need more than one boolean setting, such as „light mode“ (true) / „dark mode“ (false).

> I'm also going to leave in the code for a custom icon - just in case someone has a really wacky theme and they need an override.

This means that all use cases are covered. Excellent.

**Comment by digitaltrails** [comment]
All checked in.

 - To enable *monochrome-tray*, just set it on in settings, it default appearance is for a dark panel.
 - The second setting, *mono-light-tray*, just controls the light panel appearance, so *monochrome-tray* has to be enabled too (*monochrome-tray* is the master switch).

Changes should become apparent when the settings are saved, immediately after the application reloads (there is no need to restart).

If needed, the override file is now a SVG that should be named `$HOME/.config/vdu_controls/tray_icon.svg`.  The content of the file is assumed to be for a dark theme, and white or breeze-white will be automatically be changed to black if *monochrome-tray* is enabled (so the same file can cover dark and light).  A starter override file is in [icons/tray_icon.svg](https://github.com/digitaltrails/vdu_controls/blob/master/icons/tray_icon.svg) (editable with inkscape).

**Comment by abil76** [comment]
Great job! Updated your script and added the icons to the correct folders. Here is the result after restarting the computer (and setting it to monochrome). Thanks alot!

![2023-10-22_125821](https://github.com/digitaltrails/vdu_controls/assets/46962320/6f037e96-744f-4e16-b233-f352e860df3a)

**Comment by digitaltrails** [comment]
> Great job! Updated your script and added the icons to the correct folders. Here is the result after restarting the computer (and setting it to monochrome). Thanks alot!

Your desktop looks good. It clearly demonstrates the need for monochrome tray icon, the icon fits right in.

**In your case, you shouldn't need any special icons.** Try removing `$HOME/.config/vdu_controls/tray_icon.svg` and in ``Settings`` turn on ``monochrome tray enabled``.  That should do the trick. **If that isn't the case, that would be a bug.**

**Comment by abil76** [comment]
I did it directly without `tray_icon.svg` anyway and as you explained, enabled the `monochrome tray` setting. I just copied the `tray_icon.svg` to the `icons` folder (as a template). 
I also tried a custom icon, so I saved it directly in the config folder under the name `tray_icon.svg`. This also worked wonderfully.

**Comment by digitaltrails** [comment]
> I did it directly without `tray_icon.svg` anyway and as you explained, enabled the `monochrome tray` setting. I just copied the `tray_icon.svg` to the `icons` folder (as a template). I also tried a custom icon, so I saved it directly in the config folder under the name `tray_icon.svg`. This also worked wonderfully.

Great. Thanks for testing all the options.

**Comment by digitaltrails** [comment]
Released in [v1.20.0](https://github.com/digitaltrails/vdu_controls/tree/v1.20.0).
